-- CreateEnum
CREATE TYPE "StatusType" AS ENUM ('CLOSED', 'ONPRODUCTION');

-- CreateEnum
CREATE TYPE "LigneType" AS ENUM ('LIGNE1', 'LIGNE2');

-- CreateEnum
CREATE TYPE "ShiftType" AS ENUM ('MORNING', 'MIDDAY', 'NIGHT');

-- CreateEnum
CREATE TYPE "CategoryType" AS ENUM ('RAINSN_PLA_NONE_NO_NO_4M0845543', 'RAS_OTH_NO_NO_NPL_P_XXX_01_00_00_0', 'CAM_BRKT_SE270_WS_6F0_868_033_SE270_DRW', 'CAM_BRKT_SE216_WS_6F9_868_033_SE216_D', 'RAS_OTH_NO_PUR_NPL_RS_HFEPH2', 'FRM_SOF_EPDM_EXTR_WS_UP_PROF_SE270', 'FRM_SOF_EPDM_EXTR_WS_AEST_UP_PROF_SE270', 'FRM_SOF_EPDM_ROLL_WS_LOW_PROF_SE270', 'PROFILE_SUPERIEUR_SE216', 'LOWER_PROFIL_SE216_WITH_OPENING', 'LOWER_PROFIL_VW216', 'PROFILE_SUPERIEUR_VW216', 'FRM_FLU_TPE_ROLL_WS_P2J0_SGS_201_2242', 'SPACER_5X5_3X40_FRANCEM_EPDM_SE270', 'FRM_FLU_TPE_STRE_WS_VW276_DRAWING_040316', 'HELLA_4_7_RSA_BRACKET_JFC_BJA_B10', 'BLISTER_HELLA_4_7_RSA_NISSAN', 'AGRAFFE_PA66_C41_WS_EDGE_CLIP', 'HALTEPLATTE_R_BAS_MKF_P_N_2GA868033', 'CAMERA_PLATE_2GM_868_033_A', 'BLISTER_RAIN_SENSOR_MB_PLASTIC', 'NAVY_BLUE_PLASTIC_SPACER_26_6MM_BFC2', 'CAM_BRKT_OTH_NO_NO_PLA_2GM_868_033_C_DR', 'HALTEPLATTE_R_BAS_MKF_P_N_2GA868033B', 'VICS_BRACKET_4N0_907_720', 'LOCATOR_PIN_P21_PLA_INJ', 'COVER_BRACKET_PA66GF30_WS_PSA_CP4', 'CAB_X_OTH_WS_D_PP_N_2GM_868_033_D', 'G_C41_WS_N_PA663_CITC41WSDEM_HY_OTH', 'OTH_G_VW276_WS_X_C_PBT_N_2GA_868_033_C', 'SPACER_VW_5_3_MMX5X20_MM', 'FRM_USH_TPE_CORN_WS_PSA_C_C41_01_00_00_0', 'FRM_FLU_TPE_STRE_WS_VW276_TAB_008_899_A', 'ACT_DUP_BETAWIPE_VP04604_1L', 'PRIDUP_BETAPRIME_5404_1L', 'PRILDUP_BETAPRIME_5500_1L', 'PRIDUP_BETAPRIME_5550_1L', 'PRI_DUP_BETAPRIME_5026_1L', 'STILDUP_BETASEAL_1965_1F_300ML', 'STI_DUP_BETASEAL_1965_1F_22L', 'JINETILLO_PASO_18', 'JINETILLO_PASO_21', 'BANDE_DE_BALISAGE', 'MARQUEUR_BLEU', 'CISEAUX_DE_CERCLAGE', 'JINETILLO_MARRON_M_18_0A', 'JINETILLO_NARANJA_T_21_0A', 'CREMALLI_RES_PASO_32_VW216', 'CREMALLI_RE_C41_PASO_28_COLD_VERSION', 'RAMETTE_PAPIER_A', 'SERRE_TETE_POUR_ECRAN_FACIAL', 'ECRAN_ADAPTABLE_VISOR_BORD_METAL', 'FIELTRO_C_BLANCO_DIAMETRE_10X20_MM', 'FIELTRO_C_BLANCO_26X20X10_MM', 'TETE_DE_BIBERON_26X20X10_MM', 'T_TE_DE_PRIMAGE_D10_MM', 'T_TE_DE_PRIMAGE_D1_MODIFI', 'SCOTCH_HAUTE_TEMPERATURE', 'ETIQUETTE_BT5026', 'ETIQUETTE_VP04604', 'ETIQUETTE_BT5500', 'SCOTCH_DOUBLE_FACE', 'ETIQUETTE_BC3300', 'DRYING_BAG_10GR_ORANGE_SILICA_GEL_TYPE_0', 'SOBRE_ADHESIVO_240_X_180_MM_TRANSPAREN', 'BOLSA_PE_TRANSP_MICROPER_1550_1500X1780', 'BIBERON_PRIMER_301_100', 'LAMES_POUR_LIGNE_DE_CONTROLE', 'JUEGO_CREMALLERA_REF_09441_ESPUMA_POLIE', 'FIELTRE_D_16X20_MM', 'FIELTRO_C_BLANCO_22X20_MM', 'BAGUETTES_BOIS_POUR_RACK_CUSTODE', 'RAMETTE_PAPIER_A4', 'CAMERA_VW216_INDICE_B', 'CAMERA_VW216_INDICE_C', 'CREMALLI_RES_18_SE270_SE216', 'CREMALLI_RES_21_SE270_SE216', 'HP_LASER_JET_PRO_M404DN_CF259A', 'AUTOCOLLANTS_SE216', 'AUTOCOLLANTS_SE270', 'CAVALIERS_C41_N28_0A_COLD_VERSION', 'CREMALLI_RE_C41_PASO_40_HEATED_VERSION', 'CAVALIERS_C41_N40_0A_HEATED_VERSION', 'CR_MALLI_RES_PASO_34_VW_SEAT', 'CAVALIERS_C41_COLD', 'CREMALLI_RES_PASO_32_VW276', 'CREMALLI_RE_RACK_R006_90', 'PAQUET_DE_100_SERRE_CABLE_EN_PLASTIQUE', 'CUBE_ADH_SIF_900_E_02493', 'GANTS_NITRIL_JETABLE_NON_POUDRE', 'BOAUILLAS_WS_XPA_PARA_FIELTRO_DE_D22X2', 'BOAUILLAS_WS_DLP_L_PARA_FIELTRO_DE_D16', 'WIPEOFF_BOBINE_IND_PURE_OUATE_150M', 'CLE_DUPONT_BETACLEAN_3300_XXX', 'CRAYON_MARQUAGE_DES_DEFAUTS_STAEDTLER', 'TETE_DE_CLEANER', 'ETIQUETTE_BLANCHE_ETIKA_70MM_X_37MM', 'GANTS_ANTI_ACIDE', 'BANDE_DE_PROTECTION_VERRE', 'TABLIER_FOUR', 'VENTOUSE_PRIMAGE_VERIBOR', 'MARQUEUR_PERMANANT_NOIR_STAEDTLER_F', 'MARQUEUR_EDING_3000', 'RUBOND_IMPRIMENTE_MACHINE', 'SACHAIT_DES_GRAIN_ANTI_HUMIDIT', 'SCOTCH_TESA_50600_66X_25MM', 'ROLLO_DE_FILM_PET_80UM_VERDE_66M_X_50MM', 'GABARIT_DE_CONTROLE_C41_PROFIL_3_COTES', 'GABARIT_DE_MONTAGE_C41_PROFIL_3_COTES', 'ROLL_10000_PERMANENT_SELF_ADHESIVE_70X13', 'RUBON_3400_WAX_RESIN83MM_SUPL450M_C_25', 'GABARIT_PROFILE_SUP_RIEUR_SE216', 'GABARIT_PROFILE_SUP_RIEUR_SE270_LABIO', 'GABARIT_PROFILE_SUP_RIEUR_SE270', 'TIQUETTES_TRACABILITE_AUTOMATIQUE_PG4', 'ETIQUETTE_EN_VELIN_COLLE_S2046', 'CINTA_PLASTICA_BLANCA_66X50_TESA_4024', 'CAVALIERS_BLEU_RETOUR', 'HOUSSING', 'CAMER_C41_CVM');

-- CreateEnum
CREATE TYPE "ProblemType" AS ENUM ('DECOLLAGE', 'POSITION', 'CASSE', 'TRIANGLE', 'GAP', 'ECAILLE', 'TRAJECTOIRE_PU', 'ETAT_DES', 'CONNECTEURS_C41_H', 'BRILLANCE', 'TACHE_PRIMAGE_ZV', 'RAYURE', 'DEFAUT_INTERNE', 'GRIFFE', 'PRIMAGE_NOK', 'RETRAIT_PVB', 'TEST', 'REJET', 'TIME_OUT');

-- CreateTable
CREATE TABLE "Materials" (
    "codeSAP" TEXT NOT NULL,
    "designation" TEXT,
    "unit" TEXT,
    "typeArticle" TEXT,
    "PU" DOUBLE PRECISION,
    "quantity" INTEGER,
    "cout" DOUBLE PRECISION,
    "imputation" TEXT,
    "desImputation" TEXT,

    CONSTRAINT "Materials_pkey" PRIMARY KEY ("codeSAP")
);

-- CreateTable
CREATE TABLE "Sorties" (
    "sortieId" TEXT NOT NULL,
    "codeSAP" TEXT NOT NULL,
    "quantity" INTEGER,
    "timeStamp" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "userName" TEXT,

    CONSTRAINT "Sorties_pkey" PRIMARY KEY ("sortieId")
);

-- CreateTable
CREATE TABLE "Productions" (
    "productionId" TEXT NOT NULL,
    "sortieId" TEXT NOT NULL,
    "quantity" INTEGER,
    "wasteQuantity" INTEGER,
    "timeStamp" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "statusType" "StatusType" NOT NULL,

    CONSTRAINT "Productions_pkey" PRIMARY KEY ("productionId")
);

-- CreateTable
CREATE TABLE "Shift" (
    "id" TEXT NOT NULL,
    "shiftType" "ShiftType" NOT NULL,
    "ligneType" "LigneType" NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "technicien" TEXT,
    "totalWasted" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Shift_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WastedEntry" (
    "id" TEXT NOT NULL,
    "category" "CategoryType" NOT NULL,
    "problem" "ProblemType" NOT NULL,
    "Quantity" INTEGER NOT NULL,
    "shiftId" TEXT NOT NULL,

    CONSTRAINT "WastedEntry_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Materials_codeSAP_key" ON "Materials"("codeSAP");

-- CreateIndex
CREATE UNIQUE INDEX "Sorties_sortieId_key" ON "Sorties"("sortieId");

-- AddForeignKey
ALTER TABLE "Sorties" ADD CONSTRAINT "Sorties_codeSAP_fkey" FOREIGN KEY ("codeSAP") REFERENCES "Materials"("codeSAP") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Productions" ADD CONSTRAINT "Productions_sortieId_fkey" FOREIGN KEY ("sortieId") REFERENCES "Sorties"("sortieId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WastedEntry" ADD CONSTRAINT "WastedEntry_shiftId_fkey" FOREIGN KEY ("shiftId") REFERENCES "Shift"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
